/*
╔══════════════════════════════════════════════════════════════╗
║                 frontend/src/main.jsx                        ║
║           "The front door of the React app"                  ║
╚══════════════════════════════════════════════════════════════╝

  PREVIOUSLY: The entire backend (server, models, routes, controllers).
  Now we switch sides — from the SERVER to the BROWSER.

  WHAT IS THIS FILE?
  ──────────────────
  This is the ENTRY POINT of the React frontend. Just like server.js
  starts the backend, this file starts the frontend. It's the first
  JavaScript that runs when someone opens the website.

  FIRST PRINCIPLE — How does a React app start?
  ─────────────────────────────────────────────
  1. Browser loads index.html (a mostly empty HTML file)
  2. index.html has a <div id="root"></div> — an empty container
  3. This JavaScript file runs and "injects" the React app into that div
  4. React takes over — everything you see is generated by JavaScript

  Think of it like a video game console:
    index.html  = the TV screen (just a blank surface)
    main.jsx    = the console (plugs into the screen)
    App.jsx     = the game cartridge (the actual content)

  FIRST PRINCIPLE — The "wrapping" pattern you see here:
  ──────────────────────────────────────────────────
  <BrowserRouter>
    <AppContextProvider>
      <App />
    </AppContextProvider>
  </BrowserRouter>

  Each wrapper ADDS a capability:
    BrowserRouter      → enables URL-based navigation (React Router)
    AppContextProvider  → makes backend data available everywhere

  This is called the "Provider Pattern." Each provider is a React
  Context that SHARES data with everything inside it. Without this
  wrapping, child components couldn't access the router or the
  global app state.

  WHY WRAP IN THIS ORDER? BrowserRouter is outermost because
  even the context provider might need routing. AppContextProvider
  is inside because it might use router features.
*/

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
/*
   index.css is the global stylesheet (Tailwind CSS).
   It's imported here so it applies to EVERYTHING.
*/
import App from './App.jsx'
import { BrowserRouter } from 'react-router-dom'
import AppContextProvider from './context/AppContext.jsx'

createRoot(document.getElementById('root')).render(
  /*
     createRoot() is the React 18+ way to create a React root.
     It attaches React to the DOM element with id="root" (from index.html).

     .render() starts the rendering process — it takes JSX and
     converts it to real HTML elements in the browser.

     StrictMode is a development helper that:
       - Detects unsafe lifecycle methods
       - Warns about legacy APIs
       - Runs effects twice to catch bugs (only in dev mode)
  */
  <BrowserRouter>
  <AppContextProvider>
    <App />
  </AppContextProvider>
  </BrowserRouter>,
)

/*
  ┌─────────────────────────────────────────────────────────────┐
  │  NEXT FILE: App.jsx                                         │
  │                                                             │
  │  main.jsx just boots up. The actual app structure —         │
  │  what pages exist and how they're connected to URLs —       │
  │  is in App.jsx.                                             │
  └─────────────────────────────────────────────────────────────┘
*/
